services:
  # development database
  cinema-db:
    image: postgres:15-alpine
    container_name: cinema-dev-db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: movie_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # test database
  cinema-test-db:
    image: postgres:15-alpine
    container_name: cinema-test-db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: movie_app_test
    ports:
      - "5433:5432"

volumes:
  postgres_data: